import { useState } from "react";

const ITEMS = [
  {
    q: "What chains does baseexchangepro support?",
    a: "The protocol is native to Base. Swaps execute directly on the Base L2 with no bridging required.",
  },
  {
    q: "How is the 2% protocol fee applied?",
    a: "The fee is calculated on the output amount of each swap and shown transparently in the swap panel before you confirm. Nothing is hidden in the route.",
  },
  {
    q: "Is it custodial?",
    a: "No. Trades are fully non-custodial — your assets stay in your wallet until a swap settles on-chain.",
  },
  {
    q: "Which wallets can I connect?",
    a: "Any EVM wallet, including Base Smart Wallet with passkey sign-in, MetaMask, Coinbase Wallet, and WalletConnect.",
  },
  {
    q: "How do referral rewards pay out?",
    a: "You earn a share of the protocol fee generated by traders you refer, accrued on-chain and claimable from your dashboard.",
  },
];

export default function Faq() {
  const [open, setOpen] = useState(-1);
  return (
    <div className="faq rv">
      {ITEMS.map((item, i) => (
        <div className={`qa ${open === i ? "open" : ""}`} key={i}>
          <button className="q" onClick={() => setOpen(open === i ? -1 : i)}>
            {item.q} <span className="plus">+</span>
          </button>
          <div className="a" style={{ maxHeight: open === i ? 200 : 0 }}>
            <p>{item.a}</p>
          </div>
        </div>
      ))}
    </div>
  );
}
